<LPHEADER> 
 <TABLE BGCOLOR="#D0D0E0" BORDER="1" CELLPADDING="10"> 
<TR>  <TH>%FIELDNAME_1%</TH>  <TH>%FIELDNAME_2%</TH> <TH>%FIELDNAME_3%</TH> <TH>%FIELDNAME_4%</TH> </TR> </LPHEADER> <LPBODY> <TR> 
<TD><TT>%FIELD_1%</TT></TD>  <TD><TT>%FIELD_2%</TT></TD>  <TD><TT>%FIELD_3%</TT></TD><TD><TT>%FIELD_4%</TT></TD> </TR> 

</LPBODY> <LPFOOTER> </TABLE> </LPFOOTER> 